services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    container_name: bot
    env_file: ".env"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./crawler.db:/app/crawler.db