"""initial

Revision ID: a821cd161d33
Revises:
Create Date: 2025-04-17 19:53:07.984122

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a821cd161d33'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resources',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(length=1024), nullable=False),
        sa.Column('url', sa.String(length=1024), nullable=False),
        sa.Column('xpath', sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
